#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* custom_softsplat_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#pragma OPENCL EXTENSION cl_khr_int32_base_atomics : enable\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"enum BorderMode {\n"
" BorderMode_ZEROS=0,\n"
" BorderMode_CLAMP=1,\n"
" BorderMode_REFLECTION=2,\n"
" BorderMode_MIN=BorderMode_ZEROS,\n"
" BorderMode_MAX=BorderMode_REFLECTION\n"
"};\n"
"inline void atomic_add_float(volatile __global float *source,const float operand) { \n"
" union { \n"
" unsigned int intVal; \n"
" float floatVal; \n"
" } newVal; \n"
" union { \n"
" unsigned int intVal; \n"
" float floatVal; \n"
" } prevVal; \n"
" do { \n"
" mem_fence(CLK_GLOBAL_MEM_FENCE);\n"
" prevVal.floatVal=*source; \n"
" newVal.floatVal=prevVal.floatVal+operand; \n"
" } while (atomic_cmpxchg((volatile __global unsigned int *)source,\n"
" prevVal.intVal,newVal.intVal) \n"
" != prevVal.intVal); \n"
"} \n"
"__kernel void custom_softsplat_buf(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *flow,\n"
" __global FLOAT *output,\n"
" __private const int input_height,\n"
" __private const int input_width,\n"
" __private const int output_height,\n"
" __private const int output_width,\n"
" __private const int channels,\n"
" __private const int batch,\n"
" __private const enum BorderMode paddingMode) {\n"
" const int n=get_global_id(0);\n"
" const int c=get_global_id(1);\n"
" const int hw=get_global_id(2);\n"
" const int h=hw/input_width;\n"
" const int w=hw % input_width;\n"
" DEAL_NON_UNIFORM_DIM3(n,c,hw);\n"
" if (c >= channels) return;\n"
" const int flow_xy_stride=input_height*input_width;\n"
" const int flow_offset=n*2*flow_xy_stride+h*input_width+w;\n"
" float flow_x=flow[flow_offset];\n"
" float flow_y=flow[flow_offset+flow_xy_stride];\n"
" float fltOutputX=(float)w+flow_x;\n"
" float fltOutputY=(float)h+flow_y;\n"
" int x0=(int)floor(fltOutputX);\n"
" int y0=(int)floor(fltOutputY);\n"
" /* Bilinear weights for the four corners (NW,NE,SW,SE). */\n"
" float dx=fltOutputX-(float)x0;\n"
" float dy=fltOutputY-(float)y0;\n"
" float w_nw=(1.0f-dx)*(1.0f-dy);\n"
" float w_ne=dx*(1.0f-dy);\n"
" float w_sw=(1.0f-dx)*dy;\n"
" float w_se=dx*dy;\n"
" const int nc=n*channels+c;\n"
" const int input_offset=(nc*input_height+h)*input_width+w;\n"
" float val=(float)input[input_offset];\n"
" const int out_plane=output_height*output_width;\n"
" const int nc_out_base=nc*out_plane;\n"
" int cx[4],cy[4];\n"
" float cw[4];\n"
" cx[0]=x0; cy[0]=y0; cw[0]=w_nw;\n"
" cx[1]=x0+1; cy[1]=y0; cw[1]=w_ne;\n"
" cx[2]=x0; cy[2]=y0+1; cw[2]=w_sw;\n"
" cx[3]=x0+1; cy[3]=y0+1; cw[3]=w_se;\n"
" for (int k=0; k<4; k++) {\n"
" int ox=cx[k],oy=cy[k];\n"
" if (ox >= 0 && ox<output_width && oy >= 0 && oy<output_height) {\n"
" int out_offset=nc_out_base+oy*output_width+ox;\n"
" atomic_add_float(output+out_offset,val*cw[k]);\n"
" }\n"
" }\n"
"}\n"
;
#endif
}
